sonata_user:
    security_acl: false

    manager_type: orm # can be orm or mongodb

    impersonating:
        route: page_slug
        parameters: { path: / }

    class:
        user: App\Entity\User

    admin: # Admin Classes
        user:
            class: App\Admin\UserAdmin
            controller: '%sonata.admin.configuration.default_controller%'
            translation: SonataUserBundle

    profile:
        default_avatar: bundles/sonatauser/default_avatar.png # Default avatar displayed if the user doesn't have one

    mailer: sonata.user.mailer.default # Service used to send emails

    resetting: # Reset password configuration (must be configured)
        email:
            template: '@SonataUser/Admin/Security/Resetting/email.html.twig'
            address: sonata@localhost
            sender_name: Sonata Admin